---
abstract: 'pack your dependencies onto your script file'
author:
  - 'Matt S. Trout (mst) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::FatPacker
name: App-FatPacker
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.009006
